# Generated by Django 3.0 on 2019-12-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_user_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='building_number',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='city',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='street',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
